### ISSUE TITLE
Issue with DSDT.aml for Trackpad support

### ISSUE THREAD

**Issue by psylou** [DocSystem/razerbladehackintosh#1]
First of all, I want to thank you for all your work! You helped me alot with your EFI folder.

my Specs: RB-15 mid 2019, i7-9750h, RTX 2060.

Sadly I was only able to boot with your EFI, by deleting DSDT.aml otherwise boot crashes. Is there any other way to get trackpad working?

**Comment by DocSystem** [comment]
I think you will need to patch your own DSDT!
To do this you will need to extract them using CLOVER:
- Restart your computer
- Once you are on CLOVER press F4 to extract your DSDT to /EFI/CLOVER/ACPI/origin/
- Then start your computer on macOS (if you can, if you cannot just send me the DSDT.aml)
- Use iasl to extract DSDT.aml to DSDT.dsl
- Open the extracted DSDT.dsl with MaciASL
- Apply this [battery patch](https://github.com/DocSystem/razerbladehackintosh#battery-status)
- To patch the trackpad use [this guide](https://www.olarila.com/topic/5644-enable-i2c-trackpad-voodooi2c-not-a-guide-not-really/?tab=comments#comment-64537) (The Windows patch is the Windows 10 patch, the ACPI ID is TPD0, the APIC Pin number is ``0x5a``, the Hex for the Pin list in ``\\_SB.PCI0.GPI0`` is ``0xA2``)

**Comment by psylou** [comment]
I'm not sure if I'm able to do that. That's my DSDT.aml just in case you would do it for me. I would really appreciate that.

[DSDT.aml.zip](https://github.com/DocSystem/razerbladehackintosh/files/4208627/DSDT.aml.zip)

**Comment by DocSystem** [comment]
I don't know if it will be sufficient but try with this: [DSDT.aml.zip](https://gofile.io/?c=jNQZrg)
I don't know why but one out of two times, my computer doesn't start. Try rebooting if it doesn't work

**Comment by DocSystem** [comment]
Just to know: Are you using my config.plist? And what macOS version are you trying to install?

**Comment by psylou** [comment]
Thank you! I'll try the file right now!
I'm using your config.plist. At first, I tried Mojave. Afterwards I used Catalina. Both worked.

I got another Issue, maybe you could help me with that. I got a weird nvram.plist outside of EFI Folder in EFI root, and I have no idea, why I cant get rid of that. The next thing is, that Lilu and Whatevergreen are not giving me the graphics to work. Still have Intel UHD 630 with 7 MB.

**Comment by DocSystem** [comment]
Try pressing F10 on Clover to reset NVRAM

**Comment by psylou** [comment]
I tried. Same thing. When I delete nvram.plist. I get bootloops.

Trackpad is still not working, but I was able to boot normally with DSDT.aml. Thank you, for all your help!

**Comment by DocSystem** [comment]
Do you have VoodooI2C and VoodooI2CHID Kexts? If yes the trackpad should work!
Can you try with all my EFI folder (on a USB key for example) just by replacing my DSDT with the DSDT I sent you

**Comment by psylou** [comment]
I tried that. No luck. But I guess I have to roll back everything anyway. I had to use nvram.plist, since I installed with a dirty DMG 10.14.1 downloaded from some website. After that I was never able to boot without the usb drive I used to install that. I'm going to reset CMOS. 

Could you tell me, what RB you exactly have? i7- 9.th Gen or 8.th Gen? 

Also, I wasn't able to get the Overclocking Menu unhidden in BIOS to disable XTU Interface as mentioned in [stonevils](https://github.com/stonevil/Razer_Blade_Advanced_early_2019_Hackintosh) Guide. That should'nt be the problem right?

**Comment by DocSystem** [comment]
I have a Razer Blade 15 Base Model 2019 with RTX 2060, i7 9th gen and 512 GB SSD.
I upgraded the wifi card with a Broadcom to get wifi work in macOS and I added a second SSD using the SATA III port (Crucial MX500 1 TB). I installed macOS on the SATA SSD

**Comment by psylou** [comment]
Good to hear that we have the same specs. I also installed it on a second SSD 2TB SanDisk. But I havent bought the Wifi Module yet. Maybe that is the problem? So I'm going to delete the kext files that belong to your new wifi module.

Your DSDT.aml should then work out of the box too, right? Because we got exactly the same system.

Edit: So. No luck with everything rolled back and CMOS reset. With your DSDT.aml it reboots in the first 2 seconds and without the DSDT.aml it goes half way through. and then reboots.

**Comment by psylou** [comment]
It reboots on "gioscreenlockstate 3 hs 0 bs 0 now 0 sm 0x0". Google says it has something to do with the intel card. Using "inject Intel" and everything else didnt solve it. I'm out of ideas :( shouldnt it work, as we have the same system. Did you change anything else in bios?

EDIT: So the temporary solution is to change the Intel ID from 0x0000000 to 0x12345678.

**Comment by DocSystem** [comment]
Can you send me all your EFI Folder? I will see if I can do something

**Comment by psylou** [comment]
my EFI folder is basically your EFI folder without DSDT.aml. I can send you the newly generated DSDT.aml. So it has definitely something to do with the iGPU. Because it boots every time iGPU is not recognized (because of changing platform Id to 0x12345678).

**Comment by psylou** [comment]
That's my EFI Folder. Maybe you can find something. I would be super happy to use macOS. Neither Trackpad nor Battery is patched yet. it's my clean DSDT.aml
[EFI.zip](https://github.com/DocSystem/razerbladehackintosh/files/4219901/EFI.zip)

Could you maybe provide me pictures of your bios, with everything you changed?

**Comment by DocSystem** [comment]
For the battery, you can try with ``VirtualSMC.kext`` and ``SMCBatteryManager.kext``. I'm using them now because they are better! I will upgrade the guide later...

**Comment by DocSystem** [comment]
This issue is similar to #3 so I close it

**Comment by djtilapia** [comment]
@PTR-W not sure if you saw this, but this is what i followed. https://www.youtube.com/watch?v=oxQU3IrGqCM - seems to be running fine, everything works for the most part, trackpad, graphics, audio, battery indicator, sleep, but not native wifi. i ordered a supported wifi/bluetooth card, but right now just using a usb dongle. i also use a program called bettertouchtool for media keys so i don't need to always hold down the FN key.  one thing to note, for me, i had to disable thunderbolt settings in the bios for my trackpad to work.

**Comment by psylou** [comment]
@djtilapia Thank you so much for letting me know! Everything works for me except Ethernet. Any Idea, why? He has no Realtek8111.kext. But even with adding that kext, ethernet is still not working.

**Comment by DocSystem** [comment]
You need to remove the NullEthernet.kext from the EFI folder and also from the config.plist. OpenCore is really different from CLOVER! I was stuck on Mojave because Catalina wasn't booting. After using this guide everything was working but I modified the EFI folder (kexts changes, config...)! I will upload it soon!

**Comment by djtilapia** [comment]
also, some boots seem to be inconsistent. like sometimes the audio won't work, or the trackpad won't work, so i'll have to shutdown or restart.  the headphone input doesn't work properly, and there's no onboard mic working. also i get panics when i try to boot windows from the opencore boot menu. i tried to edit the smbios using opencore configurator but i'm unable to get imessage to work.

**Comment by steelbrain** [comment]
After some intense hair pulling on the audio not working issue mentioned above, here's a consistent data point I've found:

- Audio works without FileVault enabled
- Audio does not work, regardless of layout ID with FileVault enabled.

Everything else other than Audio continues to work tho

Edit: I am dumb, very dumb. Needed to fixup my LiluFriend config

**Comment by Tergazzi** [comment]
Hello I am having a similar issue as mentioned earlier by someone else. Whenever i reboot, its a gamble if audio or trackpad will work or not. Sometimes they both work, sometimes only audio will work and other times i get trackpad but no audio. Is there a permanent fix for this, or is it just something i have to live with when having a hackintosh?   (oh also iMessage doesnt work at all)

Specs: 2015 RB - Base model - i7, RTX 2060, 16gb RAM, 500gb upgraded SSD and 1tb upgraded SSD, upgraded wifi to broadcom.

**Comment by DocSystem** [comment]
Please use the new EFI.
Normally everything should work.
If something is not working. Please open another issue!
