### ISSUE TITLE
Cool !

### ISSUE THREAD

**Issue by augustin-bv** [DocSystem/razerbladehackintosh#2]
Nice hackintosh ! 
Finally, did you get the trackpad working and can we get Linux/Windows or Linux AND WIndows working with Clover on the same disk ?

**Comment by DocSystem** [comment]
Yes my trackpad is working : here is the [guide](https://github.com/DocSystem/razerbladehackintosh/blob/master/README.md#trackpad)
Yes it is possible to have Windows, macOS and Linux on the same disk but I do not recommend it if you have only the original Razer Blade SSD that has only 512 Gb
