### ISSUE TITLE
Can this be used for the 2020 advanced model?

### ISSUE THREAD

**Issue by carlosxfigueroa** [DocSystem/razerbladehackintosh#5]
i just got the razer blade 15 with a 2070s is this efi compatible?

**Comment by DocSystem** [comment]
I don’t know…
You can try and if it doesn’t work try another EFI (there are a lot of Razer Blade EFIs on internet)

**Comment by carlosxfigueroa** [comment]
what are your specs?

**Comment by DocSystem** [comment]
CPU: Intel Core i7-9750H
GPU: Intel UHD Graphics 630 / RTX 2060

**Comment by DocSystem** [comment]
This issue will be closed because of inactivity
